[alembic]
script_location = migrations
sqlalchemy.url = postgresql+psycopg2://postgres:postgres@localhost:5432/sa_navigator

[loggers]
keys = root,alembic,sqlalchemy

[logger_root]
level = WARN
handlers =

[logger_alembic]
level = INFO
handlers =

[logger_sqlalchemy]
level = WARN
handlers =
